### PR TITLE
add codeql config

### PR DESCRIPTION
**Pull request by TimGels**
adds quality check to codeql CI

### CODE REVIEW

**Comment by JohannesKauffmann** [comment]
Why does it say "compilation failed" and can't it find trivial types like List<> and Task<>? The code scanner is riddled with these kinds of errors, despite the green checkmark.

**Comment by TimGels** [comment]
> Why does it say "compilation failed" and can't it find trivial types like List<> and Task<>? The code scanner is riddled with these kinds of errors, despite the green checkmark.

I will look into it

**Comment by TimGels** [comment]
@JohannesKauffmann 
https://github.com/TimGels/Camera-Security-System-Server/blob/0c58bccbe60b5e67eb612b050834273ace5c634a/CSS%20Server/Models/CameraManager.cs#L37-L37
isnt there a using needed to use this? that file does not have any usings.

**Comment by JohannesKauffmann** [comment]
See https://github.com/github/codeql/issues/7086. Apparantly a known issue. Can you add the removal of the obj folder in this pull aswell?

**Comment by JohannesKauffmann** [comment]
It appears to be indeed related to the language version. On C# 9, it won't build as is. I'll create a PR soon.

**Comment by TimGels** [comment]
> It appears to be indeed related to the language version. On C# 9, it won't build as is. I'll create a PR soon.

You will downgrade the project csharp version to 9?

**Comment by JohannesKauffmann** [comment]
No, I think I'll disable the globalusings options in the csproj. I'll fix the usings then as well.

**Pull request merged**
